# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceX' do
  # Comment the next line if you don't want to use dynamic frameworks
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod "XCDYouTubeKit", "~> 2.15"
  use_frameworks!

  # Pods for SpaceX

  target 'SpaceXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpaceXUITests' do
    # Pods for testing
  end

end
